import cartolafc

api = cartolafc.Api(attempts=5)
print api.status()
print api.market()
print api.round_score()
print api.highlights()
print api.round_highlights()
print api.sponsors()
print api.rounds()
print api.matches()
print api.clubs()
print api.schemes()
print api.search_team_info_by_name('Falydos FC')
print api.get_team('Falydos FC')
print api.get_team('falydos-fc', is_slug=True)
print api.get_team_by_round('Falydos FC', 1)
print api.get_team_by_round('falydos-fc', 1, is_slug=True)
print api.search_league_info_by_name('Virtus Premier League')
